### ISSUE TITLE
Typo in author_email

### ISSUE THREAD

**Issue by brisad** [jstasiak/enum-compat#1]
Thank you for adding this package.

Got a warning when trying it out:
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'authoer_email'

**Comment by jstasiak** [comment]
You're welcome. Thank you for the feedback, this is fixed and released as 0.0.2 now.

**Comment by robbiecrypto** [comment]
https://github.com/jstasiak/enum-compat/issues/1#issuecomment-120762446 #3

**Comment by robbiecrypto** [comment]
Duplicate of #
